### ISSUE TITLE
Syntax error in <title> content

### ISSUE THREAD

**Issue by reynold1** [jdrbc/podly_pure_podcasts#39]
I replaced the two files that you updated but am now running into the following error:

=====
```
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv --python 3.12.8

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (3a7f2b)...

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>python src/main.py
Config:
{
"openai_api_key": "XXXXXXXXXX",
"openai_base_url": "https://api.openai.com/v1",
"openai_max_tokens": 4096,
"openai_model": "gpt-4o",
"openai_timeout": 300,
"output": {
"fade_ms": 3000,
"min_ad_segement_separation_seconds": 60,
"min_ad_segment_length_seconds": 14,
"min_confidence": 0.8
},
"podcasts": null,
"processing": {
"system_prompt_path": "config/system_prompt.txt",
"user_prompt_template_path": "config/user_prompt.jinja",
"num_segments_to_input_to_prompt": 30
},
"server": null,
"server_port": 5001,
"threads": 1,
"whisper": {
"whisper_type": "local",
"model": "base"
},
"remote_whisper": null,
"whisper_model": null,
"automatically_whitelist_new_episodes": true,
"number_of_episodes_to_whitelist_from_archive_of_new_feed": 1
}
Traceback (most recent call last):
File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\main.py", line 4, in
from app.feeds import add_or_refresh_feed
File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\feeds.py", line 102
<title>podly_pure_podcasts/src/app/feeds.py at main · jdrbc/podly_pure_podcasts</title>
^
SyntaxError: invalid character '·' (U+00B7)

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>
```
=====

Hopefully this is an easier error to fix!

**Comment by frrad** [comment]
Is it possible you introduced some changes while copying over the modified files from that PR? 

The referenced line in that file is empty on `main` 
https://github.com/jdrbc/podly_pure_podcasts/blob/9c9ac0628129ed9691cc7dabf654bd0dff473637/src/app/feeds.py#L102

Could you try `git fetch && git reset --hard origin/main` now that the PR is merged?

**Comment by reynold1** [comment]
I think that addressed the error! Thanks! Submitted a later error I ran into though.
