### ISSUE TITLE
Similar File to Window Error?

### ISSUE THREAD

**Issue by reynold1** [jdrbc/podly_pure_podcasts#45]
I just swapped out the revised "podcast_downloader.py" file like you suggested. I made it a little farther in the process but got stopped by what looks like a similar error:

Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pip install pipenv
Requirement already satisfied: pipenv in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (2024.4.0)
Requirement already satisfied: certifi in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (2024.8.30)
Requirement already satisfied: packaging>=22 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (24.2)
Requirement already satisfied: setuptools>=67 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (75.6.0)
Requirement already satisfied: virtualenv>=20.24.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (20.28.0)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (0.3.9)
Requirement already satisfied: filelock<4,>=3.12.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (3.16.1)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (4.3.6)

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv --python 3.12.8

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (3a7f2b)...

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>python src/main.py
Config:
{
"openai_api_key": "XXXXXXXXXX",
"openai_base_url": "https://api.openai.com/v1",
"openai_max_tokens": 4096,
"openai_model": "gpt-4o",
"openai_timeout": 300,
"output": {
"fade_ms": 3000,
"min_ad_segement_separation_seconds": 60,
"min_ad_segment_length_seconds": 14,
"min_confidence": 0.8
},
"podcasts": null,
"processing": {
"system_prompt_path": "config/system_prompt.txt",
"user_prompt_template_path": "config/user_prompt.jinja",
"num_segments_to_input_to_prompt": 30
},
"server": null,
"server_port": 5001,
"threads": 1,
"whisper": {
"whisper_type": "local",
"model": "base"
},
"remote_whisper": null,
"whisper_model": null,
"automatically_whitelist_new_episodes": true,
"number_of_episodes_to_whitelist_from_archive_of_new_feed": 1
}
INFO [alembic.runtime.migration] Context impl SQLiteImpl.
INFO [alembic.runtime.migration] Will assume non-transactional DDL.
C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\main.py:12: DeprecationWarning: deprecated
if config.podcasts is None:
INFO [waitress] Serving on http://0.0.0.0:5001/
INFO [global_logger] Fetching feed with ID: 1
INFO [global_logger] Refreshing feed with ID: 1
INFO [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO [global_logger] Feed with ID: 1 refreshed
INFO [global_logger] Generating XML for feed with ID: 1
INFO [global_logger] XML generated for feed with ID: 1
INFO [global_logger] Feed with ID: 1 fetched and XML generated
INFO [global_logger] request to download post with GUID: 6f29b2e6fda4b799a6287a081cae1789
INFO [global_logger] Downloading post: Speak to Me in French
INFO [shared.podcast_downloader] Downloading https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 into in\Speak to Me in French\Speak to Me in French.mp3...
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): [www.podtrac.com:443](http://www.podtrac.com:443/)
DEBUG [urllib3.connectionpool] [https://www.podtrac.com:443](https://www.podtrac.com/) "GET /pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): pdst.fm:443
DEBUG [urllib3.connectionpool] [https://pdst.fm:443](https://pdst.fm/) "GET /e/chrt.fm/track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 108
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): chrt.fm:443
DEBUG [urllib3.connectionpool] [https://chrt.fm:443](https://chrt.fm/) "GET /track/524GE/traffic.megaphone.fm/GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 0
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): traffic.megaphone.fm:443
DEBUG [urllib3.connectionpool] [https://traffic.megaphone.fm:443](https://traffic.megaphone.fm/) "GET /GLT1320575665.mp3?updated=1571169443 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): dcs-spotify.megaphone.fm:443
DEBUG [urllib3.connectionpool] [https://dcs-spotify.megaphone.fm:443](https://dcs-spotify.megaphone.fm/) "GET /GLT1320575665.mp3?key=dea9e4f8f932e9a1cf63fb4368239c01&request_event_id=f615f011-2447-4819-b2ea-261dcf46733f&timetoken=1734292162_2D238411A35E6AA8F2E9118FE0566858 HTTP/11" 200 63442918
INFO [shared.podcast_downloader] Download complete.
DEBUG [httpx] load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG [httpx] load_verify_locations cafile='C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\certifi\cacert.pem'
ERROR [app] Exception on /post/6f29b2e6fda4b799a6287a081cae1789.mp3 [GET]
Traceback (most recent call last):
File "C:\Users\Administrator.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
response = self.full_dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
rv = self.handle_user_exception(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\routes.py", line 81, in download_post
output_path = processor.process(post)
^^^^^^^^^^^^^^^^^^^^^^^
File "<https://github.com/beartype(podcast_processor.podcast_processor.PodcastProcessor.process) at 0x148b8c267a0>", line 32, in process
File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 84, in process
classification_dir = self.make_dirs(post, processed_audio_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<https://github.com/beartype(podcast_processor.podcast_processor.PodcastProcessor.make_dirs) at 0x148b8c26840>", line 50, in make_dirs
File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 121, in make_dirs
os.makedirs(processed_audio_dir, exist_ok=True)
File "", line 215, in makedirs
File "", line 215, in makedirs
File "", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'srv/Where Should We Begin? with Esther Perel'

**Comment by frrad** [comment]
So, given that your running my branch from https://github.com/jdrbc/podly_pure_podcasts/pull/43 I would expect it to take care of this question mark thing.

It's possible that the question mark was added to your DB before you changed to my branch and it's still there causing problems. Can you try to 

1. stop podly
1. move your DB from `./src/instance/sqlite3.db` to somewhere else (or delete it if you haven't yet set things up successfully and wouldn't be sad to lose it)
2. restart podly

and see if you continue to get the same issue?

**Comment by reynold1** [comment]
I ended up deleting the "sqlite3.db" file as suggested as tried to grab the most recent episode this time. However, I still got a very similar error message:

=====

Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pip install pipenv
Requirement already satisfied: pipenv in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (2024.4.0)
Requirement already satisfied: certifi in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (2024.8.30)
Requirement already satisfied: packaging>=22 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (24.2)
Requirement already satisfied: setuptools>=67 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (75.6.0)
Requirement already satisfied: virtualenv>=20.24.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from pipenv) (20.28.0)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (0.3.9)
Requirement already satisfied: filelock<4,>=3.12.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (3.16.1)
Requirement already satisfied: platformdirs<5,>=3.9.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from virtualenv>=20.24.2->pipenv) (4.3.6)

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv --python 3.12.8

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv install
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (3a7f2b)...

C:\Users\Administrator\Desktop\podly_pure_podcasts-main>pipenv shell
Launching subshell in virtual environment...
Microsoft Windows [Version 10.0.19045.5247]
(c) Microsoft Corporation. All rights reserved.

(podly_pure_podcasts-main-n1Rxt2gQ) C:\Users\Administrator\Desktop\podly_pure_podcasts-main>python src/main.py
Config:
 {
  "openai_api_key": "XXXXXXXXXX",
  "openai_base_url": "https://api.openai.com/v1",
  "openai_max_tokens": 4096,
  "openai_model": "gpt-4o",
  "openai_timeout": 300,
  "output": {
    "fade_ms": 3000,
    "min_ad_segement_separation_seconds": 60,
    "min_ad_segment_length_seconds": 14,
    "min_confidence": 0.8
  },
  "podcasts": null,
  "processing": {
    "system_prompt_path": "config/system_prompt.txt",
    "user_prompt_template_path": "config/user_prompt.jinja",
    "num_segments_to_input_to_prompt": 30
  },
  "server": null,
  "server_port": 5001,
  "threads": 1,
  "whisper": {
    "whisper_type": "local",
    "model": "base"
  },
  "remote_whisper": null,
  "whisper_model": null,
  "automatically_whitelist_new_episodes": true,
  "number_of_episodes_to_whitelist_from_archive_of_new_feed": 1
}
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> bae70e584468, empty message
INFO  [alembic.runtime.migration] Running upgrade bae70e584468 -> fa3a95ecd67d, audio processing paths
INFO  [alembic.runtime.migration] Running upgrade fa3a95ecd67d -> 770771437280, episode whitelist
INFO  [alembic.runtime.migration] Running upgrade 770771437280 -> 6e0e16299dcb, alternate feed ID
C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\main.py:12: DeprecationWarning: deprecated
  if config.podcasts is None:
INFO  [waitress] Serving on http://0.0.0.0:5001
INFO  [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO  [global_logger] Storing feed: Where Should We Begin? with Esther Perel
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Number of episodes to load from archive reached: 1
INFO  [global_logger] Feed stored with ID: 1
WARNI [waitress.queue] Task queue depth is 1
INFO  [global_logger] Fetching feed with ID: 1
INFO  [global_logger] Refreshing feed with ID: 1
INFO  [global_logger] Fetching feed from URL: https://feeds.megaphone.fm/ep-wswb
INFO  [global_logger] Feed with ID: 1 refreshed
INFO  [global_logger] Generating XML for feed with ID: 1
INFO  [global_logger] XML generated for feed with ID: 1
INFO  [global_logger] Feed with ID: 1 fetched and XML generated
INFO  [global_logger] request to download post with GUID: 405c706c-abf4-11ee-a295-07bd1bfe887e
INFO  [global_logger] Downloading post: Esther Calling - I Don't Want to Turn Into My Mother
INFO  [shared.podcast_downloader] Downloading https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/VMP2049575685.mp3?updated=1734368201 into in\Esther Calling  I Dont Want to Turn Into My Mother\Esther Calling  I Dont Want to Turn Into My Mother.mp3...
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): www.podtrac.com:443
DEBUG [urllib3.connectionpool] https://www.podtrac.com:443 "GET /pts/redirect.mp3/pdst.fm/e/chrt.fm/track/524GE/traffic.megaphone.fm/VMP2049575685.mp3?updated=1734368201 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): pdst.fm:443
DEBUG [urllib3.connectionpool] https://pdst.fm:443 "GET /e/chrt.fm/track/524GE/traffic.megaphone.fm/VMP2049575685.mp3?updated=1734368201 HTTP/11" 302 108
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): chrt.fm:443
DEBUG [urllib3.connectionpool] https://chrt.fm:443 "GET /track/524GE/traffic.megaphone.fm/VMP2049575685.mp3?updated=1734368201 HTTP/11" 302 0
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): traffic.megaphone.fm:443
DEBUG [urllib3.connectionpool] https://traffic.megaphone.fm:443 "GET /VMP2049575685.mp3?updated=1734368201 HTTP/11" 302 None
DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): dcs-spotify.megaphone.fm:443
DEBUG [urllib3.connectionpool] https://dcs-spotify.megaphone.fm:443 "GET /VMP2049575685.mp3?key=4638d08fe8f2ced68a9c424a39931f22&request_event_id=04d5cf9c-c144-4ae5-9101-6c1a05adce39&timetoken=1734381052_89F12E66925E07976BCC78655A5073FE HTTP/11" 200 82750128
INFO  [shared.podcast_downloader] Download complete.
ERROR [app] Exception on /post/405c706c-abf4-11ee-a295-07bd1bfe887e.mp3 [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.virtualenvs\podly_pure_podcasts-main-n1Rxt2gQ\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\app\routes.py", line 81, in download_post
    output_path = processor.process(post)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(podcast_processor.podcast_processor.PodcastProcessor.process) at 0x1d3a8121d00>", line 32, in process
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 84, in process
    classification_dir = self.make_dirs(post, processed_audio_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(podcast_processor.podcast_processor.PodcastProcessor.make_dirs) at 0x1d3a8121da0>", line 50, in make_dirs
  File "C:\Users\Administrator\Desktop\podly_pure_podcasts-main\src\podcast_processor\podcast_processor.py", line 121, in make_dirs
    os.makedirs(processed_audio_dir, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'srv/Where Should We Begin? with Esther Perel'

=====

I'm going to try another podcast with a more standard title (without punctuation) to see if that makes a difference.

Will report back ...

**Comment by frrad** [comment]
We should be able to handle even weird names >.<

Would you mind sharing the URL for the feed with this title so I can try it locally? I won't be able to truly reproduce it since I don't have a windows machine but I should at least be able to check to see the names of the folders it tries to make.

**Comment by reynold1** [comment]
Just returning after holiday break ... Here is the RSS feed for the podcast: https://feeds.megaphone.fm/ep-wswb

**Comment by frrad** [comment]
Thank you! It's much easier being able to test things myself. Hopefully it's fixed for real this time 🤞
