### ISSUE TITLE
Facing breaking errors: TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by 2600box** [jdrbc/podly_pure_podcasts#6]
Hello, 

I have been looking for something like this since ChatGPT hit the streets. I have tried using gpt-4o and docker and ubuntu 24.04 but have been focussing on windows as that is where my GPUs are.

No matter what I do, I have not had success. It seems something wrong with the Ollama api syntax. My ollama server runs fine for other ML stuff I do.

In addition to the errors below, Whisper only runs on CPU. Is that expected behaviour?

Any tips to get this working, I would be eternally grateful!

Cheers

`http://10.0.0.12:5001/download/301%20Best%20Reviews%20from%20Tour%202024.mp3?podcast_title=%5Bpodly%5D%20Beach%20Too%20Sandy%20Water%20Too%20WetPODLYPARAMSEPepisode_url=https%3A//book.trade/feed/dbe384cf-d162-4e03-bfcf-8247e9bfd2a9/item/dd179ceb-2fe9-46ac-b491-e3478b7bacb8/media.mp3^

Windows python logs:
```
2024-09-11 15:41:11,038 INFO OPENAI_API_BASE: http://127.0.0.1:11434/v1
2024-09-11 15:41:11,038 INFO OPENAI_TIMEOUT: 300
2024-09-11 15:41:11,038 INFO OPENAI_MAX_TOKENS: 4096
2024-09-11 15:41:11,038 INFO OPENAI_API_KEY: ********
2024-09-11 15:41:11,038 INFO OPENAI_MODEL: phi3:14b-medium-4k-instruct-q5_K_M
2024-09-11 15:44:16,225 INFO Downloading https://book.trade/feed/dbe384cf-d162-4e03-bfcf-8247e9bfd2a9/item/dd179ceb-2fe9-46ac-b491-e3478b7bacb8/media.mp3 into in/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3...
2024-09-11 15:44:17,223 INFO Download complete.
2024-09-11 15:44:17,237 INFO Transcribing audio from in/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3 into processing/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3/transcription
2024-09-11 15:44:17,238 INFO Using local whisper
2024-09-11 15:44:17,238 INFO Available models: ['tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large']
2024-09-11 15:44:18,031 INFO Beginning transcription
2024-09-11 15:53:15,482 INFO Transcription completed in 537.4513664245605
2024-09-11 15:53:15,493 INFO Identifying ad segments for in/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3
2024-09-11 15:53:15,494 INFO processing 2044 transcript segments

ERROR:main:Exception on /download/301 Best Reviews from Tour 2024.mp3 [GET]
Traceback (most recent call last):
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 952, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpcore\_sync\connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 832, in create_connection
    sock.settimeout(timeout)
TypeError: 'str' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\Documents\podly_pure_podcasts\src\main.py", line 51, in download
    output_path = processor.process(task)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\Documents\podly_pure_podcasts\src\podcast_processor\podcast_processor.py", line 93, in process
    self.classify(
  File "C:\Users\tiki\Documents\podly_pure_podcasts\src\podcast_processor\podcast_processor.py", line 269, in classify
    identification = self.call_model(model, system_prompt, user_prompt)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\Documents\podly_pure_podcasts\src\podcast_processor\podcast_processor.py", line 278, in call_model
    response = self.client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\resources\chat\completions.py", line 590, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 976, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 976, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\openai\_base_client.py", line 986, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

```

Docker gpt-4o logs:
```
2024-09-11 14:03:53 
2024-09-11 14:03:53 ==========
2024-09-11 14:03:53 == CUDA ==
2024-09-11 14:03:53 ==========
2024-09-11 14:03:53 
2024-09-11 14:03:53 CUDA Version 12.4.1
2024-09-11 14:03:53 
2024-09-11 14:03:53 Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
2024-09-11 14:03:53 
2024-09-11 14:03:53 This container image and its contents are governed by the NVIDIA Deep Learning Container License.
2024-09-11 14:03:53 By pulling and using the container, you accept the terms and conditions of this license:
2024-09-11 14:03:53 https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
2024-09-11 14:03:53 
2024-09-11 14:03:53 A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
2024-09-11 14:03:53 
2024-09-11 14:03:54 OPENAI_BASE_URL http://10.0.0.12:11434/v1
2024-09-11 14:03:54 OPENAI_TIMEOUT 300
2024-09-11 14:03:54 OPENAI_MAX_TOKENS 4096
2024-09-11 14:03:54 OPENAI_API_KEY ********
2024-09-11 14:03:54 OPENAI_MODEL phi3:14b-medium-4k-instruct-q5_K_M
2024-09-11 14:09:24 INFO:global_logger:Downloading https://book.trade/feed/dbe384cf-d162-4e03-bfcf-8247e9bfd2a9/item/dd179ceb-2fe9-46ac-b491-e3478b7bacb8/media.mp3 into in/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3...
2024-09-11 14:09:27 INFO:global_logger:Download complete.
2024-09-11 14:09:27 INFO:global_logger:Transcribing audio from in/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3 into processing/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3/transcription
2024-09-11 14:09:29 INFO:global_logger:Using local whisper
2024-09-11 14:09:29 INFO:global_logger:Available models: ['tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large']
2024-09-11 14:09:32 
  0%|                                               | 0.00/139M [00:00<?, ?iB/s]
  3%|█                                     | 3.73M/139M [00:00<00:03, 39.0MiB/s]
  7%|██▋                                   | 9.92M/139M [00:00<00:02, 54.2MiB/s]
 12%|████▎                                 | 15.9M/139M [00:00<00:02, 58.2MiB/s]
 16%|█████▉                                | 21.8M/139M [00:00<00:02, 59.4MiB/s]
 20%|███████▌                              | 27.7M/139M [00:00<00:01, 60.2MiB/s]
 24%|█████████▏                            | 33.7M/139M [00:00<00:01, 61.2MiB/s]
 29%|██████████▉                           | 39.7M/139M [00:00<00:01, 61.7MiB/s]
 33%|████████████▌                         | 45.8M/139M [00:00<00:01, 62.3MiB/s]
 37%|██████████████▏                       | 51.8M/139M [00:00<00:01, 62.7MiB/s]
 42%|███████████████▉                      | 57.9M/139M [00:01<00:01, 63.0MiB/s]
 46%|█████████████████▌                    | 64.1M/139M [00:01<00:01, 63.4MiB/s]
 51%|███████████████████▎                  | 70.2M/139M [00:01<00:01, 63.7MiB/s]
 55%|████████████████████▉                 | 76.5M/139M [00:01<00:01, 64.4MiB/s]
 60%|██████████████████████▋               | 82.7M/139M [00:01<00:00, 63.5MiB/s]
 64%|████████████████████████▎             | 88.7M/139M [00:01<00:00, 63.2MiB/s]
 68%|█████████████████████████▉            | 94.7M/139M [00:01<00:00, 63.1MiB/s]
 73%|████████████████████████████▍          | 101M/139M [00:01<00:00, 63.4MiB/s]
 77%|██████████████████████████████         | 107M/139M [00:01<00:00, 63.3MiB/s]
 82%|███████████████████████████████▊       | 113M/139M [00:01<00:00, 63.5MiB/s]
 86%|█████████████████████████████████▌     | 119M/139M [00:02<00:00, 63.1MiB/s]
 90%|███████████████████████████████████▎   | 125M/139M [00:02<00:00, 63.5MiB/s]
 95%|█████████████████████████████████████  | 131M/139M [00:02<00:00, 63.7MiB/s]
 99%|██████████████████████████████████████▋| 138M/139M [00:02<00:00, 63.3MiB/s]
100%|███████████████████████████████████████| 139M/139M [00:02<00:00, 62.3MiB/s]
2024-09-11 14:09:33 INFO:global_logger:Beginning transcription
2024-09-11 14:12:59 INFO:global_logger:Transcription completed in 206.00704717636108
2024-09-11 14:12:59 INFO:global_logger:Identifying ad segments for in/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3
2024-09-11 14:12:59 INFO:global_logger:processing 1447 transcript segments
2024-09-11 14:12:59 INFO:global_logger:Calling phi3:14b-medium-4k-instruct-q5_K_M
2024-09-11 14:12:59 INFO:global_logger:Calling model: phi3:14b-medium-4k-instruct-q5_K_M
2024-09-11 14:13:02 ERROR:main:Exception on /download/301 Best Reviews from Tour 2024.mp3 [GET]
2024-09-11 14:13:02 Traceback (most recent call last):
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 952, in _request
2024-09-11 14:13:02     response = self._client.send(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 914, in send
2024-09-11 14:13:02     response = self._send_handling_auth(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 942, in _send_handling_auth
2024-09-11 14:13:02     response = self._send_handling_redirects(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 979, in _send_handling_redirects
2024-09-11 14:13:02     response = self._send_single_request(request)
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1015, in _send_single_request
2024-09-11 14:13:02     response = transport.handle_request(request)
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 233, in handle_request
2024-09-11 14:13:02     resp = self._pool.handle_request(req)
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
2024-09-11 14:13:02     raise exc from None
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
2024-09-11 14:13:02     response = connection.handle_request(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
2024-09-11 14:13:02     raise exc
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
2024-09-11 14:13:02     stream = self._connect(request)
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
2024-09-11 14:13:02     stream = self._network_backend.connect_tcp(**kwargs)
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
2024-09-11 14:13:02     sock = socket.create_connection(
2024-09-11 14:13:02   File "/usr/lib/python3.10/socket.py", line 830, in create_connection
2024-09-11 14:13:02     sock.settimeout(timeout)
2024-09-11 14:13:02 TypeError: 'str' object cannot be interpreted as an integer
2024-09-11 14:13:02 
2024-09-11 14:13:02 The above exception was the direct cause of the following exception:
2024-09-11 14:13:02 
2024-09-11 14:13:02 Traceback (most recent call last):
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
2024-09-11 14:13:02     response = self.full_dispatch_request()
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
2024-09-11 14:13:02     rv = self.handle_user_exception(e)
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
2024-09-11 14:13:02     rv = self.dispatch_request()
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
2024-09-11 14:13:02     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2024-09-11 14:13:02   File "/app/src/main.py", line 55, in download
2024-09-11 14:13:02     output_path = processor.process(task)
2024-09-11 14:13:02   File "/app/src/podcast_processor/podcast_processor.py", line 92, in process
2024-09-11 14:13:02     self.classify(
2024-09-11 14:13:02   File "/app/src/podcast_processor/podcast_processor.py", line 270, in classify
2024-09-11 14:13:02     identification = self.call_model(model, system_prompt, user_prompt)
2024-09-11 14:13:02   File "/app/src/podcast_processor/podcast_processor.py", line 279, in call_model
2024-09-11 14:13:02     response = self.client.chat.completions.create(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 277, in wrapper
2024-09-11 14:13:02     return func(*args, **kwargs)
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 590, in create
2024-09-11 14:13:02     return self._post(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1240, in post
2024-09-11 14:13:02     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 921, in request
2024-09-11 14:13:02     return self._request(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 976, in _request
2024-09-11 14:13:02     return self._retry_request(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1053, in _retry_request
2024-09-11 14:13:02     return self._request(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 976, in _request
2024-09-11 14:13:02     return self._retry_request(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1053, in _retry_request
2024-09-11 14:13:02     return self._request(
2024-09-11 14:13:02   File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 986, in _request
2024-09-11 14:13:02     raise APIConnectionError(request=request) from err
2024-09-11 14:13:02 openai.APIConnectionError: Connection error.



INFO:global_logger:Calling gpt-4o
INFO:global_logger:Calling model: gpt-4o
INFO:global_logger:Calling gpt-4o
INFO:global_logger:Calling model: gpt-4o
INFO:global_logger:Calling gpt-4o
INFO:global_logger:Calling model: gpt-4o
INFO:global_logger:Calling gpt-4o
INFO:global_logger:Calling model: gpt-4o
ERROR:main:Exception on /download/301 Best Reviews from Tour 2024.mp3 [GET]
Traceback (most recent call last):
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\.virtualenvs\podly_pure_podcasts-ng9sHvHo\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\Documents\podly_pure_podcasts\src\main.py", line 55, in download
    output_path = processor.process(task)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\Documents\podly_pure_podcasts\src\podcast_processor\podcast_processor.py", line 101, in process
    ad_segments = self.get_ad_segments(transcript_segments, classification_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tiki\Documents\podly_pure_podcasts\src\podcast_processor\podcast_processor.py", line 298, in get_ad_segments
    with open(f"{classification_path}/{dir}/identification.txt", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'processing/[podly] Beach Too Sandy Water Too Wet/301 Best Reviews from Tour 2024.mp3/classification/0.0_185.9/identification.txt'


```

Current config:

```
OPENAI_API_BASE='http://127.0.0.1:11434/v1'
OPENAI_TIMEOUT=300
OPENAI_MAX_TOKENS=4096
OPENAI_API_KEY='ollama'
OPENAI_MODEL='phi3:14b-medium-4k-instruct-q5_K_M'
```

```
processing:
  system_prompt: You classify portions of transcripts
  user_prompt_template_path: config/user_prompt.jinja
  num_segments_to_input_to_prompt: 30

podcasts:
  my_podcast.rss: "https://www.example.com/original/podcast/rss/feed.rss"

output:
  fade_ms: 3000
  min_ad_segement_separation_seconds: 60
  min_ad_segment_length_seconds: 14
  min_confidence: 0.8
  ```

**Comment by frrad** [comment]
https://github.com/jdrbc/podly_pure_podcasts/blob/main/src/podcast_processor/podcast_processor.py#L281-L282
can you add some more logging here and see what you get?
